### ISSUE TITLE
Could you provide us with an input data example?

### ISSUE THREAD

**Issue by JiahangWu** [cscihkbu/CATSI#1]
Hi,

Your work is interesting. To re-implement your work, could you provide us with an input data example, please? Thank you so much!

**Comment by jakeykj** [comment]
Hi, thanks for your interest in our work. We use the official dataset offered by 2019 ICHI Data Analytics Challenge on Missing data Imputation (DACMI). It can be found in physionet: https://archive.physionet.org/physiotools/mimic-code/ichi-2019-shared-task-challenge/. After obtaining the dataset, you can unzip it and run the codes. 

I am closing this issue. If there are any further questions, please feel free to open up a new issue.
